### ISSUE TITLE
Create a yeoman generator

### ISSUE THREAD

**Issue by Davidsoff** [cjsauer/meteor-fresh#5]
I will probably do this tomorrow but it would be cool to use the yeoman generator in stead of manually having to remove the .git folder

**Comment by cjsauer** [comment]
That's a great idea. Keep me posted with your results.

**Comment by Davidsoff** [comment]
all done, generator can be found at: https://www.npmjs.com/package/generator-meteor-fresh

**Comment by cjsauer** [comment]
Just tested. Nice work!

Could you have it make a new directory to put the files in? That would run more closely with `meteor create my-new-app` command. There's also a warning about `bower install && npm install`, could we remove that? 

Lastly, I'm not too familiar with yo. Is this something we need to keep updated, or is it pulling from the latest Github release?

**Comment by Davidsoff** [comment]
sure thing. It is my first crack at doing this aswell so I'm glad it works.
I'll create the issues in the generator repo :)

I'll try and build a script that will run whenever you update the master branch of this repo.

If you find anything else just let me know ;)

**Comment by cjsauer** [comment]
I'm willing to bet there's a way for a yo generator to pull its files from Github. Then you could just point it to the tip of the master branch.

**Comment by cjsauer** [comment]
Possibly this? https://github.com/addyosmani/generator-boilerplate

**Comment by Davidsoff** [comment]
yep, thats the one I used. we'll see if this auto updates. if it doesn't it'll probably take a `git submodule update` to fix it

**Comment by Davidsoff** [comment]
your requests have been heard and implemented :)

**Comment by cjsauer** [comment]
Wonderful! Looks like the submodule approach? It appears to be pointing one commit behind HEAD on develop. Maybe I should merge develop into master and tag it as a release. Can `yo` do things like pick the latest release from a project? 

I'm trying to find an automated solution so that our updates here get picked up by `yo` without our interaction. That would be ideal. So `yo` users are always getting the latest release.

**Comment by Davidsoff** [comment]
I have pointed it to HEAD on master. Worst case there is probably a way to automate this using travis

**Comment by cjsauer** [comment]
Excellent. I'll merge develop into master and tag a release

**Comment by Davidsoff** [comment]
awesome, open up an issue on the generator repo if you updated so I can check if it auto updates ;)
