### ISSUE TITLE
Include package-kitchen

### ISSUE THREAD

**Issue by czxtm** [cjsauer/meteor-fresh#7]
Since this is package-based, you should include [package-kitchen](https://github.com/chicagogrooves/meteor-package-kitchen). It lets you easily add packages by just going to `http://localhost:3000/kitchen`. I've found it much more usable than `meteor create --package` in my package-based app.

**Comment by cjsauer** [comment]
Very cool. I'm going to play with this workflow this week and come back to this issue. Thanks for the link!

**Comment by cjsauer** [comment]
Decided to just include this as a tip in the readme as it may not match every users workflow.
